### ISSUE TITLE
[Epic] 2.5.0 Plugin Extensions compatibility status

### ISSUE THREAD

**Issue by Al12rs** [ModOrganizer2/modorganizer#1834]
With MO2 v2.5.0 and move to qt6, plugin extensions need to be updated to be continue working.
This issue tracks the 2.5.0 compatibility status for plugins (including third party).

Ideally most of these will be made compatible before 2.5.0 is released.

- [ ] https://github.com/ModOrganizer2/modorganizer/wiki/List-of-MO2-Extension-Plugins#orphaned-script-extender-save-deleter-plugin
- [ ] https://github.com/ModOrganizer2/modorganizer/wiki/List-of-MO2-Extension-Plugins#modorganizer-to-openmw
- [ ] https://github.com/ModOrganizer2/modorganizer/wiki/List-of-MO2-Extension-Plugins#merge-plugins-hide
- [ ] https://github.com/ModOrganizer2/modorganizer/wiki/List-of-MO2-Extension-Plugins#sync-mod-order
- [ ] https://github.com/ModOrganizer2/modorganizer/wiki/List-of-MO2-Extension-Plugins#conflict-deleter
- [ ] https://github.com/ModOrganizer2/modorganizer/wiki/List-of-MO2-Extension-Plugins#fix-game-registry-key
- [ ] https://github.com/ModOrganizer2/modorganizer/wiki/List-of-MO2-Extension-Plugins#game-redirector
- [ ] https://github.com/ModOrganizer2/modorganizer/wiki/List-of-MO2-Extension-Plugins#loot-preventifier
- [ ] https://github.com/ModOrganizer2/modorganizer/wiki/List-of-MO2-Extension-Plugins#mappings-dumper
- [ ] https://github.com/ModOrganizer2/modorganizer/wiki/List-of-MO2-Extension-Plugins#requiem-redirector
- [ ] https://github.com/ModOrganizer2/modorganizer/wiki/List-of-MO2-Extension-Plugins#root-builder
- [ ] https://github.com/ModOrganizer2/modorganizer/wiki/List-of-MO2-Extension-Plugins#grass-precacher
- [ ] https://github.com/ModOrganizer2/modorganizer/wiki/List-of-MO2-Extension-Plugins#sync-plugins-with-mod-order
- [ ] https://github.com/ModOrganizer2/modorganizer/wiki/List-of-MO2-Extension-Plugins#kezymas-root-builder
- [ ] https://github.com/ModOrganizer2/modorganizer/wiki/List-of-MO2-Extension-Plugins#kezymas-reinstaller
- [ ] https://github.com/ModOrganizer2/modorganizer/wiki/List-of-MO2-Extension-Plugins#kezymas-shortcutter
- [ ] https://github.com/ModOrganizer2/modorganizer/wiki/List-of-MO2-Extension-Plugins#kezymas-plugin-finder
- [ ] https://github.com/ModOrganizer2/modorganizer/wiki/List-of-MO2-Extension-Plugins#kezymas-curation-club
- [ ] https://github.com/ModOrganizer2/modorganizer/wiki/List-of-MO2-Extension-Plugins#kezymas-profile-sync
- [ ] https://github.com/ModOrganizer2/modorganizer/wiki/List-of-MO2-Extension-Plugins#broom---the-loose-file-sweeper
- [ ] https://github.com/ModOrganizer2/modorganizer/wiki/List-of-MO2-Extension-Plugins#loot-warning-checker
- [ ] https://github.com/ModOrganizer2/modorganizer/wiki/List-of-MO2-Extension-Plugins#loot-config-loader
- [ ] https://github.com/ModOrganizer2/modorganizer/wiki/List-of-MO2-Extension-Plugins#nif-preview-3d-model-viewer
- [ ] https://github.com/ModOrganizer2/modorganizer/wiki/List-of-MO2-Extension-Plugins#crash-log-tools
- [ ] https://github.com/ModOrganizer2/modorganizer/wiki/List-of-MO2-Extension-Plugins#bsa-extractor-2

**Comment by AnyOldName3** [comment]
I've intentionally not updated the SKSE co-save deleter as the issue it works around is fixed by Engine Fixes, which people should be using instead.

**Comment by JonathanFeenstra** [comment]
LOOT Warning Checker now has a [qt6 branch](https://github.com/JonathanFeenstra/modorganizer-loot-warning-checker/tree/qt6) to support v2.5.0 once it releases.
