### ISSUE TITLE
Meta Issue: List of TODO Enhancements

### ISSUE THREAD

**Issue by Al12rs** [Modorganizer2/modorganizer#464]
### Here is a list of requested and planned improvements:

- [ ] -Add button in preview dialog to hide the previewed and a label the winning file
- [ ] -Add flag for mods with hidden files
- [ ] -Add context menu option to mods with hidden files to unhide them
- [ ] -Add preview support for ini files
- [ ] -Add button to checksum to see if conflicting files are identical.
- [ ] -Saves view could do with a couple of columns to order by filetime and by name
- [ ] -Add "fold all", "unfold all" buttons in the archives tab
- [ ] -Make it possible to download other files while the "you have already this dl, do you want to re-download?" is up
- [ ] -make the flag for plugins loading BSAs check for the entire modlist and not just the origin mod.
- [ ] -add option to start a program not hooked (without MO locking)
- [ ] -make detected executables sortable
- [ ] -make categories change for each game
- [ ] -save modinfodialog dimensions
- [ ] -add list of non conflicted files
- [ ] -allow renaming downloads
- [ ] -ctrl +F to activate name filter
- [ ] -number of enabled and visible mods to the bottom of filters
- [ ] -When downloading a file again give option to delete the existing one
- [ ] -minimize on game launch toggle
- [ ] -add change game path option
- [ ] -add "doesn't contain Plugins" category or allow to "NOT" categories
- [ ] -add option to move all files from overwrite to a mod
- [ ] -change search function to only highlight the found mods and not hide the others
- [ ] -add refresh button for the downloads tab.
- [ ] -change file tree to open files on double click instead of rename. Maybe add copy and paste
- [ ] -fix export to csv
- [ ] -add CSV for plugins
- [ ] -implement parameter passthrough
- [ ] -fix drag&drop after entering a folder in overwrite
- [ ] -fill in start in automatically
- [ ] -use mod instead of Ow, let user create mod.
- [ ] -add query info to mods
- [ ] -change ignore missing data to not just use a texture folder

**Comment by Project579** [comment]
-make the flag for plugins loading BSAs check for the entire modlist and not just the origin mod.

Wouldn't that kill MO2 performance?

**Comment by Al12rs** [comment]
Not really too much, depending on how you implement it. Mo2 has an entry for each file loaded in the game (needed later for the usvfs mapping) that is already being used extensively for conflicts checking. The whole thing is pretty well done. I think there is room for performance improvements in the current conflicts checks, especially if we use existing cicles already needed to check for stuff.
Not something I plan to add soon anyway

**Comment by Freso** [comment]
Instead of making a meta issue, you could make a milestone and assign issues to that. :)

**Comment by Al12rs** [comment]
I don't really plan on doing all these off a particular release. I will just do them as I have some time. Most of these don't have a standalone issue dedicated to it. They are basically the requestes received on Discord and ideas I have myself.

**Comment by stsk1** [comment]
An enable all in separator feature?
